/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-06-05 at 19:40:46 UTC 
 * Modify at your own risk.
 */

package com.appspot.onyx_shoreline_602.treasurehuntapi;

/**
 * Service definition for Treasurehuntapi (v1).
 *
 * <p>
 * An API to manage the ids for the Treasure Hunts
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TreasurehuntapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Treasurehuntapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the treasurehuntapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://onyx-shoreline-602.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "treasurehuntapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Treasurehuntapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Treasurehuntapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "add".
   *
   * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
   * optional parameters, call the {@link Add#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param name
   * @return the request
   */
  public Add add(java.lang.String id, java.lang.String name) throws java.io.IOException {
    Add result = new Add(id, name);
    initialize(result);
    return result;
  }

  public class Add extends TreasurehuntapiRequest<com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHunt> {

    private static final String REST_PATH = "addId/{id}/{name}";

    /**
     * Create a request for the method "add".
     *
     * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
     * optional parameters, call the {@link Add#execute()} method to invoke the remote operation. <p>
     * {@link Add#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param name
     * @since 1.13
     */
    protected Add(java.lang.String id, java.lang.String name) {
      super(Treasurehuntapi.this, "POST", REST_PATH, null, com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHunt.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
    }

    @Override
    public Add setAlt(java.lang.String alt) {
      return (Add) super.setAlt(alt);
    }

    @Override
    public Add setFields(java.lang.String fields) {
      return (Add) super.setFields(fields);
    }

    @Override
    public Add setKey(java.lang.String key) {
      return (Add) super.setKey(key);
    }

    @Override
    public Add setOauthToken(java.lang.String oauthToken) {
      return (Add) super.setOauthToken(oauthToken);
    }

    @Override
    public Add setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Add) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Add setQuotaUser(java.lang.String quotaUser) {
      return (Add) super.setQuotaUser(quotaUser);
    }

    @Override
    public Add setUserIp(java.lang.String userIp) {
      return (Add) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public Add setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public Add setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @Override
    public Add set(String parameterName, Object value) {
      return (Add) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addClue".
   *
   * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
   * optional parameters, call the {@link AddClue#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param instruction1
   * @param instruction2
   * @param coordinateLat
   * @param coordinateLong
   * @return the request
   */
  public AddClue addClue(java.lang.String id, java.lang.String instruction1, java.lang.String instruction2, java.lang.Double coordinateLat, java.lang.Double coordinateLong) throws java.io.IOException {
    AddClue result = new AddClue(id, instruction1, instruction2, coordinateLat, coordinateLong);
    initialize(result);
    return result;
  }

  public class AddClue extends TreasurehuntapiRequest<com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHunt> {

    private static final String REST_PATH = "addClue/{id}/{instruction1}/{instruction2}/{coordinateLat}/{coordinateLong}";

    /**
     * Create a request for the method "addClue".
     *
     * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
     * optional parameters, call the {@link AddClue#execute()} method to invoke the remote operation.
     * <p> {@link
     * AddClue#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param instruction1
     * @param instruction2
     * @param coordinateLat
     * @param coordinateLong
     * @since 1.13
     */
    protected AddClue(java.lang.String id, java.lang.String instruction1, java.lang.String instruction2, java.lang.Double coordinateLat, java.lang.Double coordinateLong) {
      super(Treasurehuntapi.this, "POST", REST_PATH, null, com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHunt.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.instruction1 = com.google.api.client.util.Preconditions.checkNotNull(instruction1, "Required parameter instruction1 must be specified.");
      this.instruction2 = com.google.api.client.util.Preconditions.checkNotNull(instruction2, "Required parameter instruction2 must be specified.");
      this.coordinateLat = com.google.api.client.util.Preconditions.checkNotNull(coordinateLat, "Required parameter coordinateLat must be specified.");
      this.coordinateLong = com.google.api.client.util.Preconditions.checkNotNull(coordinateLong, "Required parameter coordinateLong must be specified.");
    }

    @Override
    public AddClue setAlt(java.lang.String alt) {
      return (AddClue) super.setAlt(alt);
    }

    @Override
    public AddClue setFields(java.lang.String fields) {
      return (AddClue) super.setFields(fields);
    }

    @Override
    public AddClue setKey(java.lang.String key) {
      return (AddClue) super.setKey(key);
    }

    @Override
    public AddClue setOauthToken(java.lang.String oauthToken) {
      return (AddClue) super.setOauthToken(oauthToken);
    }

    @Override
    public AddClue setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddClue) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddClue setQuotaUser(java.lang.String quotaUser) {
      return (AddClue) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddClue setUserIp(java.lang.String userIp) {
      return (AddClue) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public AddClue setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String instruction1;

    /**

     */
    public java.lang.String getInstruction1() {
      return instruction1;
    }

    public AddClue setInstruction1(java.lang.String instruction1) {
      this.instruction1 = instruction1;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String instruction2;

    /**

     */
    public java.lang.String getInstruction2() {
      return instruction2;
    }

    public AddClue setInstruction2(java.lang.String instruction2) {
      this.instruction2 = instruction2;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double coordinateLat;

    /**

     */
    public java.lang.Double getCoordinateLat() {
      return coordinateLat;
    }

    public AddClue setCoordinateLat(java.lang.Double coordinateLat) {
      this.coordinateLat = coordinateLat;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double coordinateLong;

    /**

     */
    public java.lang.Double getCoordinateLong() {
      return coordinateLong;
    }

    public AddClue setCoordinateLong(java.lang.Double coordinateLong) {
      this.coordinateLong = coordinateLong;
      return this;
    }

    @Override
    public AddClue set(String parameterName, Object value) {
      return (AddClue) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getAllClues".
   *
   * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
   * optional parameters, call the {@link GetAllClues#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAllClues getAllClues(java.lang.String id) throws java.io.IOException {
    GetAllClues result = new GetAllClues(id);
    initialize(result);
    return result;
  }

  public class GetAllClues extends TreasurehuntapiRequest<com.appspot.onyx_shoreline_602.treasurehuntapi.model.ClueCollection> {

    private static final String REST_PATH = "cluecollection/{id}";

    /**
     * Create a request for the method "getAllClues".
     *
     * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
     * optional parameters, call the {@link GetAllClues#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetAllClues#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAllClues(java.lang.String id) {
      super(Treasurehuntapi.this, "GET", REST_PATH, null, com.appspot.onyx_shoreline_602.treasurehuntapi.model.ClueCollection.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAllClues setAlt(java.lang.String alt) {
      return (GetAllClues) super.setAlt(alt);
    }

    @Override
    public GetAllClues setFields(java.lang.String fields) {
      return (GetAllClues) super.setFields(fields);
    }

    @Override
    public GetAllClues setKey(java.lang.String key) {
      return (GetAllClues) super.setKey(key);
    }

    @Override
    public GetAllClues setOauthToken(java.lang.String oauthToken) {
      return (GetAllClues) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAllClues setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAllClues) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAllClues setQuotaUser(java.lang.String quotaUser) {
      return (GetAllClues) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAllClues setUserIp(java.lang.String userIp) {
      return (GetAllClues) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetAllClues setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAllClues set(String parameterName, Object value) {
      return (GetAllClues) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getID".
   *
   * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
   * optional parameters, call the {@link GetID#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetID getID(java.lang.String id) throws java.io.IOException {
    GetID result = new GetID(id);
    initialize(result);
    return result;
  }

  public class GetID extends TreasurehuntapiRequest<com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHunt> {

    private static final String REST_PATH = "treasurehunt/{id}";

    /**
     * Create a request for the method "getID".
     *
     * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
     * optional parameters, call the {@link GetID#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetID(java.lang.String id) {
      super(Treasurehuntapi.this, "GET", REST_PATH, null, com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHunt.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetID setAlt(java.lang.String alt) {
      return (GetID) super.setAlt(alt);
    }

    @Override
    public GetID setFields(java.lang.String fields) {
      return (GetID) super.setFields(fields);
    }

    @Override
    public GetID setKey(java.lang.String key) {
      return (GetID) super.setKey(key);
    }

    @Override
    public GetID setOauthToken(java.lang.String oauthToken) {
      return (GetID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetID setQuotaUser(java.lang.String quotaUser) {
      return (GetID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetID setUserIp(java.lang.String userIp) {
      return (GetID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetID setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetID set(String parameterName, Object value) {
      return (GetID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "list".
   *
   * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
   * optional parameters, call the {@link List#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public List list() throws java.io.IOException {
    List result = new List();
    initialize(result);
    return result;
  }

  public class List extends TreasurehuntapiRequest<com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHuntCollection> {

    private static final String REST_PATH = "treasurehuntcollection";

    /**
     * Create a request for the method "list".
     *
     * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
     * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
     * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected List() {
      super(Treasurehuntapi.this, "GET", REST_PATH, null, com.appspot.onyx_shoreline_602.treasurehuntapi.model.TreasureHuntCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public List setAlt(java.lang.String alt) {
      return (List) super.setAlt(alt);
    }

    @Override
    public List setFields(java.lang.String fields) {
      return (List) super.setFields(fields);
    }

    @Override
    public List setKey(java.lang.String key) {
      return (List) super.setKey(key);
    }

    @Override
    public List setOauthToken(java.lang.String oauthToken) {
      return (List) super.setOauthToken(oauthToken);
    }

    @Override
    public List setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (List) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public List setQuotaUser(java.lang.String quotaUser) {
      return (List) super.setQuotaUser(quotaUser);
    }

    @Override
    public List setUserIp(java.lang.String userIp) {
      return (List) super.setUserIp(userIp);
    }

    @Override
    public List set(String parameterName, Object value) {
      return (List) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "remove".
   *
   * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
   * optional parameters, call the {@link Remove#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public Remove remove(java.lang.String id) throws java.io.IOException {
    Remove result = new Remove(id);
    initialize(result);
    return result;
  }

  public class Remove extends TreasurehuntapiRequest<Void> {

    private static final String REST_PATH = "id/{id}";

    /**
     * Create a request for the method "remove".
     *
     * This request holds the parameters needed by the the treasurehuntapi server.  After setting any
     * optional parameters, call the {@link Remove#execute()} method to invoke the remote operation.
     * <p> {@link
     * Remove#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected Remove(java.lang.String id) {
      super(Treasurehuntapi.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public Remove setAlt(java.lang.String alt) {
      return (Remove) super.setAlt(alt);
    }

    @Override
    public Remove setFields(java.lang.String fields) {
      return (Remove) super.setFields(fields);
    }

    @Override
    public Remove setKey(java.lang.String key) {
      return (Remove) super.setKey(key);
    }

    @Override
    public Remove setOauthToken(java.lang.String oauthToken) {
      return (Remove) super.setOauthToken(oauthToken);
    }

    @Override
    public Remove setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Remove) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Remove setQuotaUser(java.lang.String quotaUser) {
      return (Remove) super.setQuotaUser(quotaUser);
    }

    @Override
    public Remove setUserIp(java.lang.String userIp) {
      return (Remove) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public Remove setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public Remove set(String parameterName, Object value) {
      return (Remove) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Treasurehuntapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Treasurehuntapi}. */
    @Override
    public Treasurehuntapi build() {
      return new Treasurehuntapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TreasurehuntapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTreasurehuntapiRequestInitializer(
        TreasurehuntapiRequestInitializer treasurehuntapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(treasurehuntapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
