/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-06-24 at 17:13:49 UTC 
 * Modify at your own risk.
 */

package com.appspot.awesometreasurehunt.identifierapi.model;

/**
 * Model definition for Clue.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the identifierapi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Clue extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Double> coordinates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> instructions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isFoundClue;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Double> getCoordinates() {
    return coordinates;
  }

  /**
   * @param coordinates coordinates or {@code null} for none
   */
  public Clue setCoordinates(java.util.List<java.lang.Double> coordinates) {
    this.coordinates = coordinates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getInstructions() {
    return instructions;
  }

  /**
   * @param instructions instructions or {@code null} for none
   */
  public Clue setInstructions(java.util.List<java.lang.String> instructions) {
    this.instructions = instructions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsFoundClue() {
    return isFoundClue;
  }

  /**
   * @param isFoundClue isFoundClue or {@code null} for none
   */
  public Clue setIsFoundClue(java.lang.Boolean isFoundClue) {
    this.isFoundClue = isFoundClue;
    return this;
  }

  @Override
  public Clue set(String fieldName, Object value) {
    return (Clue) super.set(fieldName, value);
  }

  @Override
  public Clue clone() {
    return (Clue) super.clone();
  }

}
