/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-14 at 09:40:07 UTC 
 * Modify at your own risk.
 */

package com.cg.sjb_screens.identifierendpoint;

import com.cg.sjb_screens.identifierendpoint.model.CollectionResponseIdentifier;
import com.cg.sjb_screens.identifierendpoint.model.Identifier;
import com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient;

/**
 * Service definition for Identifierendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link IdentifierendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class IdentifierEndpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  protected IdentifierEndpoint(
			com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder builder) {
		super(builder);
		// TODO Auto-generated constructor stub
	}

// Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the Identifierendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://awesometreasurehunt.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "identifierapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public IdentifierEndpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  IdentifierEndpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getIdentifier".
   *
   * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
   * optional parameters, call the {@link GetIdentifier#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetIdentifier getIdentifier(java.lang.Long id) throws java.io.IOException {
    GetIdentifier result = new GetIdentifier(id);
    initialize(result);
    return result;
  }

  public class GetIdentifier extends IdentifierEndpointRequest<com.cg.sjb_screens.UserIdentifier> {

    private static final String REST_PATH = "identifier/{id}";

    /**
     * Create a request for the method "getIdentifier".
     *
     * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
     * optional parameters, call the {@link GetIdentifier#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetIdentifier#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetIdentifier(java.lang.Long id) {
      super(IdentifierEndpoint.this, "GET", REST_PATH, null, com.cg.sjb_screens.identifierendpoint.model.Identifier.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetIdentifier setAlt(java.lang.String alt) {
      return (GetIdentifier) super.setAlt(alt);
    }

    @Override
    public GetIdentifier setFields(java.lang.String fields) {
      return (GetIdentifier) super.setFields(fields);
    }

    @Override
    public GetIdentifier setKey(java.lang.String key) {
      return (GetIdentifier) super.setKey(key);
    }

    @Override
    public GetIdentifier setOauthToken(java.lang.String oauthToken) {
      return (GetIdentifier) super.setOauthToken(oauthToken);
    }

    @Override
    public GetIdentifier setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetIdentifier) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetIdentifier setQuotaUser(java.lang.String quotaUser) {
      return (GetIdentifier) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetIdentifier setUserIp(java.lang.String userIp) {
      return (GetIdentifier) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetIdentifier setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetIdentifier set(String parameterName, Object value) {
      return (GetIdentifier) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertIdentifier".
   *
   * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
   * optional parameters, call the {@link InsertIdentifier#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mindstorm.famousIdentifiers.entity.Identifierendpoint.model.Identifier}
   * @return the request
   */
  public InsertIdentifier insertIdentifier(com.cg.sjb_screens.identifierendpoint.model.Identifier content) throws java.io.IOException {
    InsertIdentifier result = new InsertIdentifier(content);
    initialize(result);
    return result;
  }

  public class InsertIdentifier extends IdentifierEndpointRequest<com.cg.sjb_screens.identifierendpoint.model.Identifier> {

    private static final String REST_PATH = "identifier";

    /**
     * Create a request for the method "insertIdentifier".
     *
     * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
     * optional parameters, call the {@link InsertIdentifier#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertIdentifier#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.mindstorm.famousIdentifiers.entity.Identifierendpoint.model.Identifier}
     * @since 1.13
     */
    protected InsertIdentifier(com.cg.sjb_screens.identifierendpoint.model.Identifier content) {
      super(IdentifierEndpoint.this, "POST", REST_PATH, content, com.cg.sjb_screens.identifierendpoint.model.Identifier.class);
    }

    @Override
    public InsertIdentifier setAlt(java.lang.String alt) {
      return (InsertIdentifier) super.setAlt(alt);
    }

    @Override
    public InsertIdentifier setFields(java.lang.String fields) {
      return (InsertIdentifier) super.setFields(fields);
    }

    @Override
    public InsertIdentifier setKey(java.lang.String key) {
      return (InsertIdentifier) super.setKey(key);
    }

    @Override
    public InsertIdentifier setOauthToken(java.lang.String oauthToken) {
      return (InsertIdentifier) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertIdentifier setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertIdentifier) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertIdentifier setQuotaUser(java.lang.String quotaUser) {
      return (InsertIdentifier) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertIdentifier setUserIp(java.lang.String userIp) {
      return (InsertIdentifier) super.setUserIp(userIp);
    }

    @Override
    public InsertIdentifier set(String parameterName, Object value) {
      return (InsertIdentifier) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listIdentifier".
   *
   * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
   * optional parameters, call the {@link ListIdentifier#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListIdentifier listIdentifier() throws java.io.IOException {
    ListIdentifier result = new ListIdentifier();
    initialize(result);
    return result;
  }

  public class ListIdentifier extends IdentifierEndpointRequest<com.cg.sjb_screens.identifierendpoint.model.CollectionResponseIdentifier> {

    private static final String REST_PATH = "identifier";

    /**
     * Create a request for the method "listIdentifier".
     *
     * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
     * optional parameters, call the {@link ListIdentifier#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListIdentifier#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListIdentifier() {
      super(IdentifierEndpoint.this, "GET", REST_PATH, null, com.cg.sjb_screens.identifierendpoint.model.CollectionResponseIdentifier.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListIdentifier setAlt(java.lang.String alt) {
      return (ListIdentifier) super.setAlt(alt);
    }

    @Override
    public ListIdentifier setFields(java.lang.String fields) {
      return (ListIdentifier) super.setFields(fields);
    }

    @Override
    public ListIdentifier setKey(java.lang.String key) {
      return (ListIdentifier) super.setKey(key);
    }

    @Override
    public ListIdentifier setOauthToken(java.lang.String oauthToken) {
      return (ListIdentifier) super.setOauthToken(oauthToken);
    }

    @Override
    public ListIdentifier setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListIdentifier) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListIdentifier setQuotaUser(java.lang.String quotaUser) {
      return (ListIdentifier) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListIdentifier setUserIp(java.lang.String userIp) {
      return (ListIdentifier) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListIdentifier setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListIdentifier setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListIdentifier set(String parameterName, Object value) {
      return (ListIdentifier) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeIdentifier".
   *
   * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
   * optional parameters, call the {@link RemoveIdentifier#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  /*public RemoveIdentifier removeIdentifier(java.lang.String id) throws java.io.IOException {
    RemoveIdentifier result = new RemoveIdentifier(id);
    initialize(result);
    return result;
  }*/

  

  /**
   * Create a request for the method "updateIdentifier".
   *
   * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
   * optional parameters, call the {@link UpdateIdentifier#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.mindstorm.famousIdentifiers.entity.Identifierendpoint.model.Identifier}
   * @return the request
   */
  public UpdateIdentifier updateIdentifier(com.cg.sjb_screens.identifierendpoint.model.Identifier content) throws java.io.IOException {
    UpdateIdentifier result = new UpdateIdentifier(content);
    initialize(result);
    return result;
  }

  public class UpdateIdentifier extends IdentifierEndpointRequest<com.cg.sjb_screens.identifierendpoint.model.Identifier> {

    private static final String REST_PATH = "Identifier";

    /**
     * Create a request for the method "updateIdentifier".
     *
     * This request holds the parameters needed by the the Identifierendpoint server.  After setting any
     * optional parameters, call the {@link UpdateIdentifier#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateIdentifier#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.mindstorm.famousIdentifiers.entity.Identifierendpoint.model.Identifier}
     * @since 1.13
     */
    protected UpdateIdentifier(com.cg.sjb_screens.identifierendpoint.model.Identifier content) {
      super(IdentifierEndpoint.this, "PUT", REST_PATH, content, com.cg.sjb_screens.identifierendpoint.model.Identifier.class);
    }

    @Override
    public UpdateIdentifier setAlt(java.lang.String alt) {
      return (UpdateIdentifier) super.setAlt(alt);
    }

    @Override
    public UpdateIdentifier setFields(java.lang.String fields) {
      return (UpdateIdentifier) super.setFields(fields);
    }

    @Override
    public UpdateIdentifier setKey(java.lang.String key) {
      return (UpdateIdentifier) super.setKey(key);
    }

    @Override
    public UpdateIdentifier setOauthToken(java.lang.String oauthToken) {
      return (UpdateIdentifier) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateIdentifier setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateIdentifier) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateIdentifier setQuotaUser(java.lang.String quotaUser) {
      return (UpdateIdentifier) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateIdentifier setUserIp(java.lang.String userIp) {
      return (UpdateIdentifier) super.setUserIp(userIp);
    }

    @Override
    public UpdateIdentifier set(String parameterName, Object value) {
      return (UpdateIdentifier) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Identifierendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Identifierendpoint}. */
    @Override
    public IdentifierEndpoint build() {
      return new IdentifierEndpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link IdentifierendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setIdentifierEndpointRequestInitializer(
    		IdentifierEndpointRequestInitializer IdentifierendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(IdentifierendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
