/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-09 16:41:44 UTC)
 * on 2014-06-24 at 17:13:49 UTC 
 * Modify at your own risk.
 */

package com.appspot.awesometreasurehunt.identifierapi;

/**
 * Service definition for Identifierapi (v1).
 *
 * <p>
 * An API to manage the ids for the Treasure Hunts
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link IdentifierapiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Identifierapi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the identifierapi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://awesometreasurehunt.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "identifierapi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Identifierapi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Identifierapi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "addClue".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link AddClue#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param instruction1
   * @param instruction2
   * @param coordinateLat
   * @param coordinateLong
   * @return the request
   */
  public AddClue addClue(java.lang.String id, java.lang.String instruction1, java.lang.String instruction2, java.lang.Double coordinateLat, java.lang.Double coordinateLong) throws java.io.IOException {
    AddClue result = new AddClue(id, instruction1, instruction2, coordinateLat, coordinateLong);
    initialize(result);
    return result;
  }

  public class AddClue extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.TreasureHunt> {

    private static final String REST_PATH = "addClue/{id}/{instruction1}/{instruction2}/{coordinateLat}/{coordinateLong}";

    /**
     * Create a request for the method "addClue".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link AddClue#execute()} method to invoke the remote operation.
     * <p> {@link
     * AddClue#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param instruction1
     * @param instruction2
     * @param coordinateLat
     * @param coordinateLong
     * @since 1.13
     */
    protected AddClue(java.lang.String id, java.lang.String instruction1, java.lang.String instruction2, java.lang.Double coordinateLat, java.lang.Double coordinateLong) {
      super(Identifierapi.this, "POST", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.TreasureHunt.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.instruction1 = com.google.api.client.util.Preconditions.checkNotNull(instruction1, "Required parameter instruction1 must be specified.");
      this.instruction2 = com.google.api.client.util.Preconditions.checkNotNull(instruction2, "Required parameter instruction2 must be specified.");
      this.coordinateLat = com.google.api.client.util.Preconditions.checkNotNull(coordinateLat, "Required parameter coordinateLat must be specified.");
      this.coordinateLong = com.google.api.client.util.Preconditions.checkNotNull(coordinateLong, "Required parameter coordinateLong must be specified.");
    }

    @Override
    public AddClue setAlt(java.lang.String alt) {
      return (AddClue) super.setAlt(alt);
    }

    @Override
    public AddClue setFields(java.lang.String fields) {
      return (AddClue) super.setFields(fields);
    }

    @Override
    public AddClue setKey(java.lang.String key) {
      return (AddClue) super.setKey(key);
    }

    @Override
    public AddClue setOauthToken(java.lang.String oauthToken) {
      return (AddClue) super.setOauthToken(oauthToken);
    }

    @Override
    public AddClue setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddClue) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddClue setQuotaUser(java.lang.String quotaUser) {
      return (AddClue) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddClue setUserIp(java.lang.String userIp) {
      return (AddClue) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public AddClue setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String instruction1;

    /**

     */
    public java.lang.String getInstruction1() {
      return instruction1;
    }

    public AddClue setInstruction1(java.lang.String instruction1) {
      this.instruction1 = instruction1;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String instruction2;

    /**

     */
    public java.lang.String getInstruction2() {
      return instruction2;
    }

    public AddClue setInstruction2(java.lang.String instruction2) {
      this.instruction2 = instruction2;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double coordinateLat;

    /**

     */
    public java.lang.Double getCoordinateLat() {
      return coordinateLat;
    }

    public AddClue setCoordinateLat(java.lang.Double coordinateLat) {
      this.coordinateLat = coordinateLat;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double coordinateLong;

    /**

     */
    public java.lang.Double getCoordinateLong() {
      return coordinateLong;
    }

    public AddClue setCoordinateLong(java.lang.Double coordinateLong) {
      this.coordinateLong = coordinateLong;
      return this;
    }

    @Override
    public AddClue set(String parameterName, Object value) {
      return (AddClue) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addIdentifier".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link AddIdentifier#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @param name
   * @return the request
   */
  public AddIdentifier addIdentifier(java.lang.String id, java.lang.String name) throws java.io.IOException {
    AddIdentifier result = new AddIdentifier(id, name);
    initialize(result);
    return result;
  }

  public class AddIdentifier extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.Identifier> {

    private static final String REST_PATH = "addId/{id}/{name}";

    /**
     * Create a request for the method "addIdentifier".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link AddIdentifier#execute()} method to invoke the remote
     * operation. <p> {@link AddIdentifier#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @param name
     * @since 1.13
     */
    protected AddIdentifier(java.lang.String id, java.lang.String name) {
      super(Identifierapi.this, "POST", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.Identifier.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
    }

    @Override
    public AddIdentifier setAlt(java.lang.String alt) {
      return (AddIdentifier) super.setAlt(alt);
    }

    @Override
    public AddIdentifier setFields(java.lang.String fields) {
      return (AddIdentifier) super.setFields(fields);
    }

    @Override
    public AddIdentifier setKey(java.lang.String key) {
      return (AddIdentifier) super.setKey(key);
    }

    @Override
    public AddIdentifier setOauthToken(java.lang.String oauthToken) {
      return (AddIdentifier) super.setOauthToken(oauthToken);
    }

    @Override
    public AddIdentifier setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddIdentifier) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddIdentifier setQuotaUser(java.lang.String quotaUser) {
      return (AddIdentifier) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddIdentifier setUserIp(java.lang.String userIp) {
      return (AddIdentifier) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public AddIdentifier setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public AddIdentifier setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @Override
    public AddIdentifier set(String parameterName, Object value) {
      return (AddIdentifier) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addTreasureHunt".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link AddTreasureHunt#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @param name
   * @return the request
   */
  public AddTreasureHunt addTreasureHunt(java.lang.String id, java.lang.String name) throws java.io.IOException {
    AddTreasureHunt result = new AddTreasureHunt(id, name);
    initialize(result);
    return result;
  }

  public class AddTreasureHunt extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.TreasureHunt> {

    private static final String REST_PATH = "addTreasureHunt/{id}/{name}";

    /**
     * Create a request for the method "addTreasureHunt".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link AddTreasureHunt#execute()} method to invoke the remote
     * operation. <p> {@link AddTreasureHunt#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @param name
     * @since 1.13
     */
    protected AddTreasureHunt(java.lang.String id, java.lang.String name) {
      super(Identifierapi.this, "POST", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.TreasureHunt.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
    }

    @Override
    public AddTreasureHunt setAlt(java.lang.String alt) {
      return (AddTreasureHunt) super.setAlt(alt);
    }

    @Override
    public AddTreasureHunt setFields(java.lang.String fields) {
      return (AddTreasureHunt) super.setFields(fields);
    }

    @Override
    public AddTreasureHunt setKey(java.lang.String key) {
      return (AddTreasureHunt) super.setKey(key);
    }

    @Override
    public AddTreasureHunt setOauthToken(java.lang.String oauthToken) {
      return (AddTreasureHunt) super.setOauthToken(oauthToken);
    }

    @Override
    public AddTreasureHunt setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddTreasureHunt) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddTreasureHunt setQuotaUser(java.lang.String quotaUser) {
      return (AddTreasureHunt) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddTreasureHunt setUserIp(java.lang.String userIp) {
      return (AddTreasureHunt) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public AddTreasureHunt setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public AddTreasureHunt setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @Override
    public AddTreasureHunt set(String parameterName, Object value) {
      return (AddTreasureHunt) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getID".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link GetID#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetID getID(java.lang.String id) throws java.io.IOException {
    GetID result = new GetID(id);
    initialize(result);
    return result;
  }

  public class GetID extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.Identifier> {

    private static final String REST_PATH = "identifier/{id}";

    /**
     * Create a request for the method "getID".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link GetID#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetID#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetID(java.lang.String id) {
      super(Identifierapi.this, "GET", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.Identifier.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetID setAlt(java.lang.String alt) {
      return (GetID) super.setAlt(alt);
    }

    @Override
    public GetID setFields(java.lang.String fields) {
      return (GetID) super.setFields(fields);
    }

    @Override
    public GetID setKey(java.lang.String key) {
      return (GetID) super.setKey(key);
    }

    @Override
    public GetID setOauthToken(java.lang.String oauthToken) {
      return (GetID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetID setQuotaUser(java.lang.String quotaUser) {
      return (GetID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetID setUserIp(java.lang.String userIp) {
      return (GetID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetID setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetID set(String parameterName, Object value) {
      return (GetID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getTreasureHuntByID".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link GetTreasureHuntByID#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetTreasureHuntByID getTreasureHuntByID(java.lang.String id) throws java.io.IOException {
    GetTreasureHuntByID result = new GetTreasureHuntByID(id);
    initialize(result);
    return result;
  }

  public class GetTreasureHuntByID extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.TreasureHunt> {

    private static final String REST_PATH = "treasurehunt/{id}";

    /**
     * Create a request for the method "getTreasureHuntByID".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link GetTreasureHuntByID#execute()} method to invoke the remote
     * operation. <p> {@link GetTreasureHuntByID#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTreasureHuntByID(java.lang.String id) {
      super(Identifierapi.this, "GET", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.TreasureHunt.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTreasureHuntByID setAlt(java.lang.String alt) {
      return (GetTreasureHuntByID) super.setAlt(alt);
    }

    @Override
    public GetTreasureHuntByID setFields(java.lang.String fields) {
      return (GetTreasureHuntByID) super.setFields(fields);
    }

    @Override
    public GetTreasureHuntByID setKey(java.lang.String key) {
      return (GetTreasureHuntByID) super.setKey(key);
    }

    @Override
    public GetTreasureHuntByID setOauthToken(java.lang.String oauthToken) {
      return (GetTreasureHuntByID) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTreasureHuntByID setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTreasureHuntByID) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTreasureHuntByID setQuotaUser(java.lang.String quotaUser) {
      return (GetTreasureHuntByID) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTreasureHuntByID setUserIp(java.lang.String userIp) {
      return (GetTreasureHuntByID) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetTreasureHuntByID setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTreasureHuntByID set(String parameterName, Object value) {
      return (GetTreasureHuntByID) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getTreasureHuntsForId".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link GetTreasureHuntsForId#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetTreasureHuntsForId getTreasureHuntsForId(java.lang.String id) throws java.io.IOException {
    GetTreasureHuntsForId result = new GetTreasureHuntsForId(id);
    initialize(result);
    return result;
  }

  public class GetTreasureHuntsForId extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.TreasureHuntCollection> {

    private static final String REST_PATH = "treasurehuntcollection/{id}";

    /**
     * Create a request for the method "getTreasureHuntsForId".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link GetTreasureHuntsForId#execute()} method to invoke the
     * remote operation. <p> {@link GetTreasureHuntsForId#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTreasureHuntsForId(java.lang.String id) {
      super(Identifierapi.this, "GET", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.TreasureHuntCollection.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTreasureHuntsForId setAlt(java.lang.String alt) {
      return (GetTreasureHuntsForId) super.setAlt(alt);
    }

    @Override
    public GetTreasureHuntsForId setFields(java.lang.String fields) {
      return (GetTreasureHuntsForId) super.setFields(fields);
    }

    @Override
    public GetTreasureHuntsForId setKey(java.lang.String key) {
      return (GetTreasureHuntsForId) super.setKey(key);
    }

    @Override
    public GetTreasureHuntsForId setOauthToken(java.lang.String oauthToken) {
      return (GetTreasureHuntsForId) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTreasureHuntsForId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTreasureHuntsForId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTreasureHuntsForId setQuotaUser(java.lang.String quotaUser) {
      return (GetTreasureHuntsForId) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTreasureHuntsForId setUserIp(java.lang.String userIp) {
      return (GetTreasureHuntsForId) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetTreasureHuntsForId setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTreasureHuntsForId set(String parameterName, Object value) {
      return (GetTreasureHuntsForId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "list".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link List#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public List list() throws java.io.IOException {
    List result = new List();
    initialize(result);
    return result;
  }

  public class List extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.IdentifierCollection> {

    private static final String REST_PATH = "identifiercollection";

    /**
     * Create a request for the method "list".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
     * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected List() {
      super(Identifierapi.this, "GET", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.IdentifierCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public List setAlt(java.lang.String alt) {
      return (List) super.setAlt(alt);
    }

    @Override
    public List setFields(java.lang.String fields) {
      return (List) super.setFields(fields);
    }

    @Override
    public List setKey(java.lang.String key) {
      return (List) super.setKey(key);
    }

    @Override
    public List setOauthToken(java.lang.String oauthToken) {
      return (List) super.setOauthToken(oauthToken);
    }

    @Override
    public List setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (List) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public List setQuotaUser(java.lang.String quotaUser) {
      return (List) super.setQuotaUser(quotaUser);
    }

    @Override
    public List setUserIp(java.lang.String userIp) {
      return (List) super.setUserIp(userIp);
    }

    @Override
    public List set(String parameterName, Object value) {
      return (List) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTreasureHunts".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link ListTreasureHunts#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTreasureHunts listTreasureHunts() throws java.io.IOException {
    ListTreasureHunts result = new ListTreasureHunts();
    initialize(result);
    return result;
  }

  public class ListTreasureHunts extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.TreasureHuntCollection> {

    private static final String REST_PATH = "treasurehuntcollection";

    /**
     * Create a request for the method "listTreasureHunts".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link ListTreasureHunts#execute()} method to invoke the remote
     * operation. <p> {@link ListTreasureHunts#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTreasureHunts() {
      super(Identifierapi.this, "GET", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.TreasureHuntCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTreasureHunts setAlt(java.lang.String alt) {
      return (ListTreasureHunts) super.setAlt(alt);
    }

    @Override
    public ListTreasureHunts setFields(java.lang.String fields) {
      return (ListTreasureHunts) super.setFields(fields);
    }

    @Override
    public ListTreasureHunts setKey(java.lang.String key) {
      return (ListTreasureHunts) super.setKey(key);
    }

    @Override
    public ListTreasureHunts setOauthToken(java.lang.String oauthToken) {
      return (ListTreasureHunts) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTreasureHunts setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTreasureHunts) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTreasureHunts setQuotaUser(java.lang.String quotaUser) {
      return (ListTreasureHunts) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTreasureHunts setUserIp(java.lang.String userIp) {
      return (ListTreasureHunts) super.setUserIp(userIp);
    }

    @Override
    public ListTreasureHunts set(String parameterName, Object value) {
      return (ListTreasureHunts) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeIdentifier".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link RemoveIdentifier#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveIdentifier removeIdentifier(java.lang.String id) throws java.io.IOException {
    RemoveIdentifier result = new RemoveIdentifier(id);
    initialize(result);
    return result;
  }

  public class RemoveIdentifier extends IdentifierapiRequest<Void> {

    private static final String REST_PATH = "id/{id}";

    /**
     * Create a request for the method "removeIdentifier".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link RemoveIdentifier#execute()} method to invoke the remote
     * operation. <p> {@link RemoveIdentifier#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveIdentifier(java.lang.String id) {
      super(Identifierapi.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveIdentifier setAlt(java.lang.String alt) {
      return (RemoveIdentifier) super.setAlt(alt);
    }

    @Override
    public RemoveIdentifier setFields(java.lang.String fields) {
      return (RemoveIdentifier) super.setFields(fields);
    }

    @Override
    public RemoveIdentifier setKey(java.lang.String key) {
      return (RemoveIdentifier) super.setKey(key);
    }

    @Override
    public RemoveIdentifier setOauthToken(java.lang.String oauthToken) {
      return (RemoveIdentifier) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveIdentifier setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveIdentifier) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveIdentifier setQuotaUser(java.lang.String quotaUser) {
      return (RemoveIdentifier) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveIdentifier setUserIp(java.lang.String userIp) {
      return (RemoveIdentifier) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveIdentifier setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveIdentifier set(String parameterName, Object value) {
      return (RemoveIdentifier) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeTreasureHunt".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link RemoveTreasureHunt#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveTreasureHunt removeTreasureHunt(java.lang.String id) throws java.io.IOException {
    RemoveTreasureHunt result = new RemoveTreasureHunt(id);
    initialize(result);
    return result;
  }

  public class RemoveTreasureHunt extends IdentifierapiRequest<Void> {

    private static final String REST_PATH = "treasurehunt/{id}";

    /**
     * Create a request for the method "removeTreasureHunt".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link RemoveTreasureHunt#execute()} method to invoke the remote
     * operation. <p> {@link RemoveTreasureHunt#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveTreasureHunt(java.lang.String id) {
      super(Identifierapi.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveTreasureHunt setAlt(java.lang.String alt) {
      return (RemoveTreasureHunt) super.setAlt(alt);
    }

    @Override
    public RemoveTreasureHunt setFields(java.lang.String fields) {
      return (RemoveTreasureHunt) super.setFields(fields);
    }

    @Override
    public RemoveTreasureHunt setKey(java.lang.String key) {
      return (RemoveTreasureHunt) super.setKey(key);
    }

    @Override
    public RemoveTreasureHunt setOauthToken(java.lang.String oauthToken) {
      return (RemoveTreasureHunt) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveTreasureHunt setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveTreasureHunt) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveTreasureHunt setQuotaUser(java.lang.String quotaUser) {
      return (RemoveTreasureHunt) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveTreasureHunt setUserIp(java.lang.String userIp) {
      return (RemoveTreasureHunt) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveTreasureHunt setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveTreasureHunt set(String parameterName, Object value) {
      return (RemoveTreasureHunt) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setClueCompletedForTHForUser".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link SetClueCompletedForTHForUser#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @param thID
   * @param clueNo
   * @return the request
   */
  public SetClueCompletedForTHForUser setClueCompletedForTHForUser(java.lang.String id, java.lang.String thID, java.lang.Integer clueNo) throws java.io.IOException {
    SetClueCompletedForTHForUser result = new SetClueCompletedForTHForUser(id, thID, clueNo);
    initialize(result);
    return result;
  }

  public class SetClueCompletedForTHForUser extends IdentifierapiRequest<Void> {

    private static final String REST_PATH = "setClueCompletedForTHForUser/{id}/{thID}/{clueNo}";

    /**
     * Create a request for the method "setClueCompletedForTHForUser".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link SetClueCompletedForTHForUser#execute()} method to invoke
     * the remote operation. <p> {@link SetClueCompletedForTHForUser#initialize(com.google.api.client.
     * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @param thID
     * @param clueNo
     * @since 1.13
     */
    protected SetClueCompletedForTHForUser(java.lang.String id, java.lang.String thID, java.lang.Integer clueNo) {
      super(Identifierapi.this, "POST", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.thID = com.google.api.client.util.Preconditions.checkNotNull(thID, "Required parameter thID must be specified.");
      this.clueNo = com.google.api.client.util.Preconditions.checkNotNull(clueNo, "Required parameter clueNo must be specified.");
    }

    @Override
    public SetClueCompletedForTHForUser setAlt(java.lang.String alt) {
      return (SetClueCompletedForTHForUser) super.setAlt(alt);
    }

    @Override
    public SetClueCompletedForTHForUser setFields(java.lang.String fields) {
      return (SetClueCompletedForTHForUser) super.setFields(fields);
    }

    @Override
    public SetClueCompletedForTHForUser setKey(java.lang.String key) {
      return (SetClueCompletedForTHForUser) super.setKey(key);
    }

    @Override
    public SetClueCompletedForTHForUser setOauthToken(java.lang.String oauthToken) {
      return (SetClueCompletedForTHForUser) super.setOauthToken(oauthToken);
    }

    @Override
    public SetClueCompletedForTHForUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetClueCompletedForTHForUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetClueCompletedForTHForUser setQuotaUser(java.lang.String quotaUser) {
      return (SetClueCompletedForTHForUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetClueCompletedForTHForUser setUserIp(java.lang.String userIp) {
      return (SetClueCompletedForTHForUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public SetClueCompletedForTHForUser setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String thID;

    /**

     */
    public java.lang.String getThID() {
      return thID;
    }

    public SetClueCompletedForTHForUser setThID(java.lang.String thID) {
      this.thID = thID;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer clueNo;

    /**

     */
    public java.lang.Integer getClueNo() {
      return clueNo;
    }

    public SetClueCompletedForTHForUser setClueNo(java.lang.Integer clueNo) {
      this.clueNo = clueNo;
      return this;
    }

    @Override
    public SetClueCompletedForTHForUser set(String parameterName, Object value) {
      return (SetClueCompletedForTHForUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setTHCompletedForUser".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link SetTHCompletedForUser#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @param thID
   * @return the request
   */
  public SetTHCompletedForUser setTHCompletedForUser(java.lang.String id, java.lang.String thID) throws java.io.IOException {
    SetTHCompletedForUser result = new SetTHCompletedForUser(id, thID);
    initialize(result);
    return result;
  }

  public class SetTHCompletedForUser extends IdentifierapiRequest<Void> {

    private static final String REST_PATH = "setTHCompletedTHForUser/{id}/{thID}";

    /**
     * Create a request for the method "setTHCompletedForUser".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link SetTHCompletedForUser#execute()} method to invoke the
     * remote operation. <p> {@link SetTHCompletedForUser#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @param thID
     * @since 1.13
     */
    protected SetTHCompletedForUser(java.lang.String id, java.lang.String thID) {
      super(Identifierapi.this, "POST", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.thID = com.google.api.client.util.Preconditions.checkNotNull(thID, "Required parameter thID must be specified.");
    }

    @Override
    public SetTHCompletedForUser setAlt(java.lang.String alt) {
      return (SetTHCompletedForUser) super.setAlt(alt);
    }

    @Override
    public SetTHCompletedForUser setFields(java.lang.String fields) {
      return (SetTHCompletedForUser) super.setFields(fields);
    }

    @Override
    public SetTHCompletedForUser setKey(java.lang.String key) {
      return (SetTHCompletedForUser) super.setKey(key);
    }

    @Override
    public SetTHCompletedForUser setOauthToken(java.lang.String oauthToken) {
      return (SetTHCompletedForUser) super.setOauthToken(oauthToken);
    }

    @Override
    public SetTHCompletedForUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetTHCompletedForUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetTHCompletedForUser setQuotaUser(java.lang.String quotaUser) {
      return (SetTHCompletedForUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetTHCompletedForUser setUserIp(java.lang.String userIp) {
      return (SetTHCompletedForUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public SetTHCompletedForUser setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String thID;

    /**

     */
    public java.lang.String getThID() {
      return thID;
    }

    public SetTHCompletedForUser setThID(java.lang.String thID) {
      this.thID = thID;
      return this;
    }

    @Override
    public SetTHCompletedForUser set(String parameterName, Object value) {
      return (SetTHCompletedForUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setTreasureHuntsForId".
   *
   * This request holds the parameters needed by the the identifierapi server.  After setting any
   * optional parameters, call the {@link SetTreasureHuntsForId#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public SetTreasureHuntsForId setTreasureHuntsForId(java.lang.String id) throws java.io.IOException {
    SetTreasureHuntsForId result = new SetTreasureHuntsForId(id);
    initialize(result);
    return result;
  }

  public class SetTreasureHuntsForId extends IdentifierapiRequest<com.appspot.awesometreasurehunt.identifierapi.model.Identifier> {

    private static final String REST_PATH = "setTreasureHuntsForId/{id}";

    /**
     * Create a request for the method "setTreasureHuntsForId".
     *
     * This request holds the parameters needed by the the identifierapi server.  After setting any
     * optional parameters, call the {@link SetTreasureHuntsForId#execute()} method to invoke the
     * remote operation. <p> {@link SetTreasureHuntsForId#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected SetTreasureHuntsForId(java.lang.String id) {
      super(Identifierapi.this, "POST", REST_PATH, null, com.appspot.awesometreasurehunt.identifierapi.model.Identifier.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public SetTreasureHuntsForId setAlt(java.lang.String alt) {
      return (SetTreasureHuntsForId) super.setAlt(alt);
    }

    @Override
    public SetTreasureHuntsForId setFields(java.lang.String fields) {
      return (SetTreasureHuntsForId) super.setFields(fields);
    }

    @Override
    public SetTreasureHuntsForId setKey(java.lang.String key) {
      return (SetTreasureHuntsForId) super.setKey(key);
    }

    @Override
    public SetTreasureHuntsForId setOauthToken(java.lang.String oauthToken) {
      return (SetTreasureHuntsForId) super.setOauthToken(oauthToken);
    }

    @Override
    public SetTreasureHuntsForId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetTreasureHuntsForId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetTreasureHuntsForId setQuotaUser(java.lang.String quotaUser) {
      return (SetTreasureHuntsForId) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetTreasureHuntsForId setUserIp(java.lang.String userIp) {
      return (SetTreasureHuntsForId) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public SetTreasureHuntsForId setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public SetTreasureHuntsForId set(String parameterName, Object value) {
      return (SetTreasureHuntsForId) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Identifierapi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Identifierapi}. */
    @Override
    public Identifierapi build() {
      return new Identifierapi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link IdentifierapiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setIdentifierapiRequestInitializer(
        IdentifierapiRequestInitializer identifierapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(identifierapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
